---
- name: Create .kube directory for user
  ansible.builtin.file:
    path: "{{ kubeconfig_base_path }}"
    state: directory    
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: Copy k3s config to .kube directory for user
  ansible.builtin.copy:
    src: "{{ k3s_config_path }}"
    dest: "{{ kubeconfig_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    remote_src: true
  become: true

- name: Set ownership of config file for user
  ansible.builtin.file:
    path: "{{ kubeconfig_file }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true

- name: Set KUBECONFIG environment variable for user
  ansible.builtin.lineinfile:
    path: "{{ bashrc_path }}"
    line: "export KUBECONFIG={{ kubeconfig_file }}"
    state: present
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Make sure .bashrc is sourced so user gets variable
  ansible.builtin.shell: source {{ bashrc_path }}
  args:
     executable: /bin/bash
  changed_when: false